interfaz/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.index, name='index'),
	path('progress', views.progress, name='progress'),
	path('ajax/getHwType', views.get_hwType, name='getHwType'),
	path('ajax/getDbSpec', views.get_dbSpec, name='getDbSpec'),
	path('ajax/readFile', views.readFile, name='readFile'),
	path('ajax/readLogs', views.readLogs, name='readLogs'),
]

plataforma/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('interfaz/', include('interfaz.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

interfaz/models.py
from django.db import models
from .validators import validate_file

# Create your models here.

class Rbdms(models.Model):
	name = models.CharField(max_length=15)
	def __str__(self):
		return self.name


class HardwareType(models.Model):
	name = models.CharField(max_length=10)
	specifications = models.CharField(max_length=1000)
	def __str__(self):
		return self.name


class OSType(models.Model):
	name = models.CharField(max_length=20)
	def __str__(self):
		return self.name


class Test(models.Model):
	SCALE_CHOICES = [(5,'5'), (10,'10'), (15,'15'), (20,'20'),]

	rdbms = models.ManyToManyField(Rbdms)
	hw_type = models.ForeignKey(HardwareType, on_delete=models.CASCADE)
	hw_spec = models.CharField(max_length=1000, blank=True)
	os_type = models.ForeignKey(OSType, on_delete=models.CASCADE)
	scale = models.IntegerField(choices=SCALE_CHOICES, default=10, help_text="TPC-C Workload: Un valor de 10 produce 2GB de data inicial")
	db1File = models.FileField(blank=True, null=True, help_text="Extensión .cnf", validators=[validate_file])
	db2File = models.FileField(blank=True, null=True, help_text="Extensión .conf", validators=[validate_file])
	db3File = models.FileField(blank=True, null=True, help_text="Extensión .cnf", validators=[validate_file])

interfaz/forms.py
from django import forms
from .models import Rbdms, HardwareType, OSType, Test

class TestForm(forms.ModelForm):
	class Meta:
		model = Test
		fields = '__all__'

		labels = {
			'rdbms': 'Seleccione el/los RDBMS',
			'hw_type': 'Configuración de hardware',
			'hw_spec': '',
			'os_type': 'Sistema Operativo',
			'scale':'Scale',
			'db1File': 'Configuración para MySQL',
			'db2File': 'Configuración para PostgreSQL',
			'db3File': 'Configuración para MariaDB',
		}

		widgets = {
			'rdbms': forms.CheckboxSelectMultiple(attrs={"class":"form-control"}),
			'hw_type': forms.Select(attrs={"class":"form-control", "onchange":"getHwType(this.value);"}),
			'hw_spec': forms.Textarea(attrs={'readonly':True, 'rows':8}),
			'os_type': forms.Select(attrs={"class":"form-control"}),
			'scale': forms.Select(attrs={"class":"form-control"}),
			'db1File': forms.ClearableFileInput(attrs={'class':'form-control', 'disabled':True}),
			'db2File': forms.ClearableFileInput(attrs={'class':'form-control', 'disabled':True}),
			'db3File': forms.ClearableFileInput(attrs={'class':'form-control', 'disabled':True}),
		}

interfaz/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.template import RequestContext
from django.contrib import messages
from .models import Rbdms, HardwareType, OSType, Test
from .forms import TestForm
from subprocess import Popen, getoutput
from django.conf import settings
import os

# Create your views here.

def index(request):
	if(request.method == 'POST'):
		form = TestForm(request.POST, request.FILES)
		#request.FILES['file'] para acceder a los archivos
		if(form.is_valid()):
			print("form is valid")
			rdbmss = form.cleaned_data.get('rdbms')
			db1, *dbs = list(rdbmss)
			db2, db3 = '', ''
			dbCount = 1
			if(len(dbs) >= 1):
				db2 = dbs[0]
				dbCount+=1
			if(len(dbs) == 2):
				db3 = dbs[1]
				dbCount+=1
			hwT = form.cleaned_data.get('hw_type')
			osT = form.cleaned_data.get('os_type')
			scale = form.cleaned_data.get('scale')
			if(int(availNodes(hwT))==0):
				print("No hay maquinas disponibles")
				messages.error(request, 'No hay maquinas %s disponibles' %str(hwT))
				return render(request, 'index.html', {'form':form})
			db1fX, db2fX, db3fX = '', '', ''
			db1File = form.cleaned_data.get('db1File')
			db2File = form.cleaned_data.get('db2File')
			db3File = form.cleaned_data.get('db3File')
			if(db1File):
				handle_uploaded_file(db1File, "mysql.cnf")
				db1fX = 'exist'
			if(db2File):
				handle_uploaded_file(db2File, "postgresql.conf")
				db2fX = 'exist'
			if(db3File):
				handle_uploaded_file(db3File, "mariadb.cnf")
				db3fX = 'exist'
			Popen(['bash','tools/bin/cloudlab.sh',str(hwT),str(osT),str(scale),str(db1),str(db2),str(db3),str(db1fX),str(db2fX),str(db3fX)])
			request.session['db1'] = str(db1)
			request.session['db2'] = str(db2)
			request.session['db3'] = str(db3)
			request.session['hwT'] = str(hwT)
			request.session['osT'] = str(osT)
			request.session['dbCount'] = dbCount
			return redirect('progress')
	else:
		print("carga")
		location = os.path.join(settings.MEDIA_ROOT, 'logs.txt')
		if(os.path.exists(location)):
			os.remove(location)
		form = TestForm()
	return render(request, 'index.html', {'form':form})

def progress(request):
	db1 = request.session['db1']
	db2 = request.session['db2']
	db3 = request.session['db3']
	return render(request, 'progress.html', {'db1':db1, 'db2':db2, 'db3':db3})

def availNodes(code):
	command = "curl -s -k https://emulab.net/portal/frontpage.php | grep "+str(code)+" -C 2 | tail -1 | sed 's/>/</g' | cut -d'<' -f3"
	return getoutput(command)

def get_hwType(request):
	pk = request.GET.get('value')
	spec = HardwareType.objects.get(pk=pk).specifications
	return JsonResponse({'spec':spec})

def get_dbSpec(request):
	pk = request.GET.get('value')
	spec = DbConfig.objects.get(pk=pk).specifications
	return JsonResponse({'spec':spec})

def file_len(fname):
	with open(fname) as f:
		for i, l in enumerate(f):
			pass
	return i + 1

def readFile(request):
	path = os.path.join(settings.BASE_DIR, 'output.txt')
	f = open(path)
	lines = f.readlines()
	line = lines[-1]
	line2 = lines[-2]
	dbCount = request.session['dbCount']
	return JsonResponse({'line':line, 'dbCount':dbCount, 'line2':line2})

def readLogs(request):
	os.makedirs("media", exist_ok=True)
	Popen(['bash','tools/bin/logs.sh'])
	location = os.path.join(settings.MEDIA_ROOT, 'logs.txt')
	lines=""
	if(os.path.exists(location)):
		f = open(location)
		lines = f.read()
		f.close()
	return JsonResponse({'lines':lines})

def handle_uploaded_file(file, name):
	os.makedirs("media", exist_ok=True)
	path = os.path.join(settings.MEDIA_ROOT, name)
	fconf = open(path, 'wb+')
	for chunk in file.chunks():
		fconf.write(chunk)
	fconf.close() 

interfaz/templates/alert.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}

interfaz/templates/index.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block extraheader %}
<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
{% endblock extraheader %}

{% block content %}
{% include 'alert.html' %}
<form method='POST' id='testForm' enctype="multipart/form-data" novalidate>
	{% csrf_token %}
	<div class="row">
		<div class="col-12">
    		<label class="col-form-label">{{ form.rdbms.label }}</label>
    		<div class="row justify-content-center">
    			<div class="form-check form-check-inline">
	    			{% for value, text in form.rdbms.field.choices %}
	    			<div class="col-4">
	    				<div class="custom-control custom-checkbox image-checkbox">
	    					<input name="{{ form.rdbms.name }}" type="checkbox" class="custom-control-input" value="{{ value }}" id="id_rdbms_{{ forloop.counter0 }}">
	    					<label class="custom-control-label" for="id_rdbms_{{ forloop.counter0 }}">
	    						{% if text == 'MySQL' %}
				                	<img src="{% static 'img/mysql.png' %}" alt="{{ text }}" class="img-fluid dbc">
				                {% elif text == 'PostgreSQL' %}
				                	<img src="{% static 'img/postgresql.png' %}" alt="{{ text }}" class="img-fluid dbc">
				                {% else %}
				                	<img src="{% static 'img/mariadb.png' %}" alt="{{ text }}" class="img-fluid dbc">
	    						{% endif %}
				            </label>
						</div>
					</div>
	    			{% endfor %}
	    		</div>
    		</div>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-4 col-12">
			{{ form.db1File|as_crispy_field }}
		</div>
		<div class="col-sm-4 col-12">
			{{ form.db2File|as_crispy_field }}
		</div>
		<div class="col-sm-4 col-12">
			{{ form.db3File|as_crispy_field }}
		</div>
	</div>
	<div class="row">
		<div class="col-sm-3 col-12">
			{{ form.scale|as_crispy_field }}
		</div>
	</div>
	<div class="row">
		<div class="col-sm-6 col-12">
			{{ form.hw_type|as_crispy_field }}
			{{ form.hw_spec|as_crispy_field }}
		</div>
		<div class="col-sm-6 col-12">
			{{ form.os_type|as_crispy_field }}
		</div>
	</div>
	<div class="row">
		<div class="col-sm-6 col-12 align-items-center" id="div_button">
			<button type="submit" class="btn btn-info">Ejecutar</button>
		</div>
	</div>
</form>
<br>
{% endblock content %}
{% block extrafooter %}
<script type="text/javascript">
	function getHwType(value){
		console.log(value);
		$.ajax({
			url: '{% url "getHwType" %}',
			data: {
				'value': value
			},
			success: function(data){
				$('#id_hw_spec').val(data.spec);
			}
		});
	}

	$(document).ready(function(){
		$('#id_rdbms_0').change(function(){
			if($('#id_rdbms_0').is(':checked')){
				document.getElementById("id_db1File").disabled = false;
			} else {
				document.getElementById("id_db1File").disabled = true;
			}
		});
		$('#id_rdbms_1').change(function(){
			if($('#id_rdbms_1').is(':checked')){
				document.getElementById("id_db2File").disabled = false;
			} else {
				document.getElementById("id_db2File").disabled = true;
			}
		});
		$('#id_rdbms_2').change(function(){
			if($('#id_rdbms_2').is(':checked')){
				document.getElementById("id_db3File").disabled = false;
			} else {
				document.getElementById("id_db3File").disabled = true;
			}
		});
	});
	
</script>
{% endblock extrafooter %}

interfaz/templates/progress.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block extraheader %}
<link rel="stylesheet" type="text/css" href="{% static 'css/progress.css' %}">
{% endblock extraheader %}

{% block content %}
<div class="col-12">
	<div class="title"><h3>Creación de experimento</h3></div>
	<div class="spinner-border text-light" role="status" id="experimentLoad">
		<span class="visually-hidden"> </span>
	</div>
	<div class="row align-items-center d-none" id="experimentStart">
		<span class="ml-3 mr-2">Iniciando máquina</span><div class="spinner-grow spinner-grow-sm text-light" role="status"></div>
	</div>
	<div class="row align-items-center d-none" id="experimentReady">
		<span class="ml-3 mr-2">Experimento Listo</span><i class="fas fa-check"></i>
	</div>
	<div class="row align-items-center d-none" id="experimentError">
		<span class="ml-3 mr-2">Error al crear experimento, no se pueden realizar pruebas</span><i class="fas fa-exclamation-triangle"></i>
	</div>
</div>
<br><br>
<div class="col-12">
	<div class="title"><h3>Pruebas de rendimiento</h3></div>
	<div class="row">
		<div class="col-4">
			<div class="test-title">
			{% if db1 == "MySQL" %}<h4>MySQL</h4>{% endif %}
			{% if db1 == "PostgreSQL" %}<h4>PostgreSQL</h4>{% endif %}
			{% if db1 == "MariaDB" %}<h4>MariaDB</h4>{% endif %}
			</div>
			<div class="spinner-border text-light" role="status" id="db1Load">
  				<span class="visually-hidden"> </span>
			</div>
			<div class="row align-items-center d-none" id="db1Start">
				<span class="ml-3 mr-2">Empezando pruebas</span><div class="spinner-grow spinner-grow-sm text-light" role="status"></div>
			</div>
			<div class="row align-items-center d-none" id="db1Ready">
				<span class="ml-3 mr-2">Pruebas terminadas</span><i class="fas fa-check"></i>
			</div>
		</div>
		{% if db2 != "" %}
		<div class="col-4">
			<div class="test-title">
			{% if db2 == "PostgreSQL" %}<h4>PostgreSQL</h4>{% endif %}
			{% if db2 == "MariaDB" %}<h4>MariaDB</h4>{% endif %}
			</div>
			<div class="spinner-border text-light" role="status" id="db2Load">
  				<span class="visually-hidden"> </span>
			</div>
			<div class="row align-items-center d-none" id="db2Start">
				<span class="ml-3 mr-2">Empezando pruebas</span><div class="spinner-grow spinner-grow-sm text-light" role="status"></div>
			</div>
			<div class="row align-items-center d-none" id="db2Ready">
				<span class="ml-3 mr-2">Pruebas terminadas</span><i class="fas fa-check"></i>
			</div>
		</div>
		{% endif %}
		{% if db3 != "" %}
		<div class="col-4">
			<div class="test-title"><h4>MariaDB</h4></div>
			<div class="spinner-border text-light" role="status" id="db3Load">
  				<span class="visually-hidden"> </span>
			</div>
			<div class="row align-items-center d-none" id="db3Start">
				<span class="ml-3 mr-2">Empezando pruebas</span><div class="spinner-border spinner-border-sm text-light" role="status"></div>
			</div>
			<div class="row align-items-center d-none" id="db3Ready">
				<span class="ml-3 mr-2">Pruebas terminadas</span><i class="fas fa-check"></i>
			</div>
		</div>
		{% endif %}
	</div>
</div>
<br><br>
<div class="col-12">
	{% if db1 == "MySQL" %}
	<div class="btn-group">
		<button type="button" class="btn btn-info dropdown-toggle disabled mysqlBtn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			Ver Resultados MySQL
		</button>
		<div class="dropdown-menu">
			<a class="dropdown-item" href="//node.comp-rdbms.espol-sched.emulab.net/graph/d/mysql-instance-summary/mysql-instance-summary" rel="noopener noreferrer" target="_blank">Resumen de instancia MySQL</a>
			<a class="dropdown-item" href="//node.comp-rdbms.espol-sched.emulab.net/graph/d/mysql-instance-compare/mysql-instances-compare" rel="noopener noreferrer" target="_blank">Comparación de instancias MySQL</a>
			<a class="dropdown-item" href="//node.comp-rdbms.espol-sched.emulab.net/graph/d/mysql-instance-overview/mysql-instances-overview" rel="noopener noreferrer" target="_blank">Detalles generales de instancias MySQL</a>
			<a class="dropdown-item" href="//node.comp-rdbms.espol-sched.emulab.net/graph/d/pmm-qan/pmm-query-analytics" rel="noopener noreferrer" target="_blank">Query Analytics</a>
			<a class="dropdown-item" href="//node.comp-rdbms.espol-sched.emulab.net/graph/d/mysql-performance-schema/mysql-performance-schema-details" rel="noopener noreferrer" target="_blank">Detalles del rendimiento del schema</a>
			<a class="dropdown-item" href="//node.comp-rdbms.espol-sched.emulab.net/graph/d/mysql-commandhandler-compare/mysql-command-handler-counters-compare" rel="noopener noreferrer" target="_blank">Comparación de comandos y handlers</a>
			<a class="dropdown-item" href="//node.comp-rdbms.espol-sched.emulab.net/graph/d/mysql-waitevents-analysis/mysql-wait-event-analyses-details" rel="noopener noreferrer" target="_blank">Eventos de espera</a>
		</div>
	</div>
	{% endif %}
	{% if db1 == "PostgreSQL" or db2 == "PostgreSQL" %}
	<div class="btn-group">
		<button type="button" class="btn btn-info dropdown-toggle disabled postgresBtn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			Ver Resultados PostgreSQL
		</button>
		<div class="dropdown-menu">
			<a class="dropdown-item" href="//node.comp-rdbms.espol-sched.emulab.net/graph/d/postgresql-instance-summary/postgresql-instance-summary" rel="noopener noreferrer" target="_blank">Resumen de instancia Postgresql</a>
			<a class="dropdown-item" href="//node.comp-rdbms.espol-sched.emulab.net/graph/d/postgresql-instance-compare/postgresql-instances-compare" rel="noopener noreferrer" target="_blank">Comparación de instancias Postgresql</a>
			<a class="dropdown-item" href="//node.comp-rdbms.espol-sched.emulab.net/graph/d/postgresql-instance-overview/postgresql-instances-overview" rel="noopener noreferrer" target="_blank">Detalles generales de instancias Postgresql</a>
			<a class="dropdown-item" href="//node.comp-rdbms.espol-sched.emulab.net/graph/d/pmm-qan/pmm-query-analytics" rel="noopener noreferrer" target="_blank">Query Analytics</a>
		</div>
	</div>
	{% endif %}
	{% if  db1 == "MariaDB" or db2 == "MariaDB" or db3 == "MariaDB" %}
	<div class="btn-group">
		<button type="button" class="btn btn-info dropdown-toggle disabled mariaBtn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			Ver Resultados MariaDB
		</button>
		<div class="dropdown-menu">
			<a class="dropdown-item" href="//node.comp-rdbms.espol-sched.emulab.net/graph/d/mysql-instance-summary/mysql-instance-summary" rel="noopener noreferrer" target="_blank">Resumen de instancia MySQL</a>
			<a class="dropdown-item" href="//node.comp-rdbms.espol-sched.emulab.net/graph/d/mysql-instance-compare/mysql-instances-compare" rel="noopener noreferrer" target="_blank">Comparación de instancias MySQL</a>
			<a class="dropdown-item" href="//node.comp-rdbms.espol-sched.emulab.net/graph/d/mysql-instance-overview/mysql-instances-overview" rel="noopener noreferrer" target="_blank">Detalles generales de instancias MySQL</a>
			<a class="dropdown-item" href="//node.comp-rdbms.espol-sched.emulab.net/graph/d/pmm-qan/pmm-query-analytics" rel="noopener noreferrer" target="_blank">Query Analytics</a>
			<a class="dropdown-item" href="//node.comp-rdbms.espol-sched.emulab.net/graph/d/mysql-performance-schema/mysql-performance-schema-details" rel="noopener noreferrer" target="_blank">Detalles del rendimiento del schema</a>
			<a class="dropdown-item" href="//node.comp-rdbms.espol-sched.emulab.net/graph/d/mysql-commandhandler-compare/mysql-command-handler-counters-compare" rel="noopener noreferrer" target="_blank">Comparación de comandos y handlers</a>
			<a class="dropdown-item" href="//node.comp-rdbms.espol-sched.emulab.net/graph/d/mysql-waitevents-analysis/mysql-wait-event-analyses-details" rel="noopener noreferrer" target="_blank">Eventos de espera</a>
		</div>
	</div>
	{% endif %}
</div>
<div class="col-12 mt-2">
	<div class="btn-group">
		<a class="btn btn-secondary" href="{% url 'index' %}">Atrás</a>
	</div>
</div>
<br>
<div class="col-12">
	<div class="row">
		<div class="col-6">
			<h3>Logs de la ejecución de las pruebas</h3>
		</div>
		<div class="col-6">
			<a class="btn btn-info float-right disabled btnLogs" href="/media/logs.txt" download>Descargar logs</a>
		</div>
	</div>	
</div>
<br>
<div class="col-12 align-items-center scroll">
</div>
{% endblock content %}
{% block extrafooter %}
<script type="text/javascript">
	function readFile(){
		$.ajax({
			url: '{% url "readFile" %}',
			success: function(data){
				console.log(data.line);
				console.log("Bases:"+data.dbCount);
				if(data.line2.match("^Estado")){
					var ch = data.line2.split(":");
					console.log(ch[1]);
					if(ch[1].trim() === "failed"){
						$("div#experimentLoad").addClass("d-none");
						$("div#experimentError").removeClass("d-none");
						$("div#db1Load").addClass("d-none");
						$("div#db2Load").addClass("d-none");
						$("div#db3Load").addClass("d-none");
					}
				}
				if(data.line.match("^SetUp")){
					var ch = data.line.split(":");
					console.log(ch[1]);
					if(ch[1].trim() === "0"){
						$("div#experimentLoad").addClass("d-none");
						$("div#experimentStart").removeClass("d-none");
					}
					if(ch[1].trim() === "1"){
						$("div#experimentStart").addClass("d-none");
						$("div#experimentReady").removeClass("d-none");
					}
				}
				if(data.line.match("^Empezando")){
					var ch = data.line.split(":");
					var dbS = ch[1].split("b");
					var dbLoad = "#db"+dbS[1].trim()+"Load"
					var dbStart = "#db"+dbS[1].trim()+"Start";
					$(dbLoad).addClass("d-none");
					$(dbStart).removeClass("d-none");
					if(window.eval(ch[1]) == 0){
						eval(ch[1]+" = 1");
						window.countDB++;
					}
				}
				if(data.line.match("^Terminaron")){
					var ch = data.line.split(":");
					var dbF = ch[1].split("b");
					var dbStartF = "#db"+dbF[1].trim()+"Start"
					var dbReady = "#db"+dbF[1].trim()+"Ready";
					$(dbStartF).addClass("d-none");
					$(dbReady).removeClass("d-none");
					if(data.dbCount == window.countDB){
						console.log("Entra");
						$(".mysqlBtn").removeClass("disabled");
						$(".postgresBtn").removeClass("disabled");
						$(".mariaBtn").removeClass("disabled");
						$(".btnLogs").removeClass("disabled");
					}
				}
			}
		});
	}

	function readLogs(){
		$.ajax({
			url: '{% url "readLogs" %}',
			success: function(data){
				output=data.lines;
				output = output.toString().replace(/(?:\r\n|\r|\n)/g, '<br>');
				$(".scroll").html(output);
				var messageBody = document.querySelector('.scroll');
				messageBody.scrollTop = messageBody.scrollHeight - messageBody.clientHeight;
			}
		});
	}
	$(document).ready(function(){
		//TODO: Acceso a countDB
		countDB = 0;
		db1 = 0; db2 = 0; db3 = 0;
		setInterval(readFile, 32000);
		setInterval(readLogs,60000);
	});
	var messageBody = document.querySelector('.scroll');
	messageBody.scrollTop = messageBody.scrollHeight - messageBody.clientHeight;
</script>
{% endblock extrafooter %}

templates/base.html
{% load static %}
{% load bootstrap4 %}
{% load fontawesome_5 %}

<!doctype "html5">

<html lang="en" class="full-height">

<head>
	<meta charset="utf-8">
	<title>
		{% block title %}
			{{ page_title|default:"Rendimiento de RDBMS" }}
		{% endblock title %}
	</title>
	<meta name="viewport" content="width=device-width">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
	{% bootstrap_css %}
	{% fontawesome_5_static %}
	
	{% block extraheader %}
	{% endblock extraheader %}
</head>

<body>
	<div class="container-fluid">
		<header>
			<div class="row">
				<div class="col-3">
					<img class="img-fluid" src="{% static 'img/espol-logo.jpg' %}" alt="logo ESPOL">
				</div>
				<div class="col-9 d-flex justify-content-center align-items-center">
					<h1>Comparación de rendimiento de RDBMS</h1>
				</div>
			</div>
		</header>
		<div class="row mb-5">
			<div class="col-12 col-xl-12">
				{% block content %}
				{% endblock content %}
			</div>
		</div>
		<footer class="navbar fixed-bottom justify-content-center">
				© ESPOL 2020. Todos los derechos reservados
		</footer>
	</div>
	<!--<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>-->
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
	{% block extrafooter %}
	{% endblock extrafooter %}
</body>